import { Red_Hat_Display , DM_Sans } from 'next/font/google';
import Header from "@/widgets/Header";
import Footer from '@/widgets/Footer';
import '../style/global.scss';
import GlobalProviders from '@/components/GlobalProviders';
import { SpeedInsights } from "@vercel/speed-insights/next"

const fontPrimary = DM_Sans({
  subsets: ['latin'],
  variable: '--ff-primary',
  weight: ['300', '400', '600', '700'],
  display: "swap",
  adjustFontFallback: false
})

export const metadata = {
  title: 'Bashar Ahammed | Frontend Developer , Interactive Developer, UI Designer, ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fontPrimary.className} style={{'--ff-primary' : fontPrimary.variable}}>
        <GlobalProviders>
          <Header />
          {children}
          <Footer />
        </GlobalProviders>
          <SpeedInsights/>
      </body>
    </html>
  )
}

