import { Red_Hat_Display } from 'next/font/google';
import Header from "@/widgets/Header";
import Footer from '@/widgets/Footer';
import '../style/global.scss';
import GlobalProviders from '@/components/GlobalProviders';

const fontPrimary = Red_Hat_Display({
  subsets: ['latin'],
  variable: '--ff-primary',
  weight: ['300', '400', '500', '600', '700'],
  display: "swap",
  
})

export const metadata = {
  title: 'EducationTechPlus',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fontPrimary.className} style={{'--ff-primary' : fontPrimary.variable}}>
        <GlobalProviders>
          <Header />
          {children}
          <Footer />
        </GlobalProviders>
      </body>
    </html>
  )
}

